services:
  - type: web
    name: api-empresas-chile
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: empresas-chile-db
          property: connectionString

databases:
  - name: empresas-chile-db
    databaseName: empresas_chile
    user: katty